ci: Enhance CI workflow with version tagging and validation
Added support for version tags in CI workflow and validated SemVer tags during release creation.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,6 +9,8 @@ on:
       - '**.mod'
       - '**.sum'
       - 'Dockerfile'
+    tags:
+      - 'v*.*.*'
     
   workflow_dispatch:
 
@@ -135,13 +137,16 @@ jobs:
       - name: set docker tag
         id: set_docker_tag
         run: |
-           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
+            echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+            echo "docker_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
+          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
             echo "DOCKER_TAG=snapshot" >> $GITHUB_ENV
             echo "docker_tag=snapshot" >> $GITHUB_OUTPUT
-            else
+          else
             echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV
             echo "docker_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
-            fi
+          fi
 
       - name: Build and push
         uses: docker/build-push-action@v7
@@ -177,4 +182,34 @@ jobs:
         run: |
           docker stop faker-api-test
           docker rm faker-api-test
+
+  release:
+    runs-on: ubuntu-latest
+    needs:
+      - test
+      - coverage
+      - docker-build
+      - docker-smoke-test
+    if: startsWith(github.ref, 'ref/tags/v')
+    permissions:
+      contents: write
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v6.0.1
+
+      - name: Validate SemVer tag
+        run: |
+          TAG="${GITHUB_REF#refs/tags/}"
+          if [[ ! "$TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+            echo "Invalid semver tag: $TAG"
+          exit 1
+          fi
+          echo "Validated tag: $TAG"
+
+      - name: create Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: ${{ github.ref_name }}
+          generate_release_notes: true
   
