ci: Correct test summary output and update Docker build steps in CI workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,7 +25,7 @@ jobs:
         run: |
           go mod tidy
           go vet -v ./... && echo "✅ go vet: No issues found." >> $GITHUB_STEP_SUMMARY || echo "❌ go vet: Issues found." >> $GITHUB_STEP_SUMMARY
-          go test -v ./... && echo "✅ go test: All tests passed." >> $GITHUB_STEP_SUMMARY || echo "❌ go test: Some tests failed." >> $
+          go test -v ./... && echo "✅ go test: All tests passed." >> $GITHUB_STEP_SUMMARY || echo "❌ go test: Some tests failed." >> $GITHUB_STEP_SUMMARY
         
   build:
     runs-on: ubuntu-latest
@@ -54,14 +54,26 @@ jobs:
       - name: checkout code
         uses: actions/checkout@v6
 
+      - name: Docker meta
+        id: meta
+        uses: docker/metadata-action@v6
+        with:
+          images: faker-api
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v4
       
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v4
       
+      - name: set docker tag
+        run: |
+           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+            echo "DOCKER_TAG=snapshot" >> $GITHUB_ENV else
+            echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV
+
       - name: Build and push
         uses: docker/build-push-action@v7
         with:
           push: false
-          tags: user/app:latest
+          tags: faker-api:${{ env.DOCKER_TAG }}
